# Generated by Django 4.2.4 on 2023-10-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='Brand_Name',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='Link',
        ),
    ]
