# Generated by Django 4.2.7 on 2023-11-24 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_customer_wallet_bal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_deleted",
            new_name="deleted",
        ),
    ]
