# Generated by Django 4.2.7 on 2023-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_alter_product_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100),
        ),
    ]
