# Generated by Django 4.2.7 on 2023-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_alter_product_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
