# Generated by Django 4.2.7 on 2023-11-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0010_alter_category_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
